
name: Newman run

on:
  push:
    branches:
      - main 
      
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create dir for report
        run: |
          mkdir testArtifacts
          

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 

      - name: Install Newman and reporters 
        run: |
          npm install newman newman-reporter-htmlextra --save-dev

      - name: Run Test
        run: npx newman run Geographql.postman_collection.json -e geographql_test.postman_environment.json -r cli,htmlextra

      - name: Report
        uses: actions/upload-artifact@v4.6.0 # ou a versão mais recente
        with:
          name: Reports
          path: newman
        
